### PR TITLE
Create .fixtures.yml

### PR DESCRIPTION
**Pull request by SourceDoctor**
add missing fixtures.yml

### CODE REVIEW

**Comment by xaque208** [comment]
thank you for putting this up.  I think this file needs to be located in the `spec/` directory, but its been a while so I might remember wrong.

**Comment by SourceDoctor** [comment]
PDK create such files in Repository root

**Comment by xaque208** [comment]
Okay, thank you for the clarification.  The tests are failing, but I don't have time today to see why.  Do they pass locally for you?

**Comment by SourceDoctor** [comment]
travis failed before also, it's something on master

**Comment by xaque208** [comment]
That sounds right, but I think the fixtures you are submitting in this PR may fix it.

**Comment by SourceDoctor** [comment]
nope
Travis misses : /etc/openvpn/openvpn.conf

**Pull request merged**
