### PR TITLE
fix missing dependencies

### PR DESCRIPTION
**Pull request by SourceDoctor**
add missing stdlib dependency to metadata.json

### CODE REVIEW

**Comment by xaque208** [comment]
Thank you for the PR.  I think to make the tests happy again, we'll need a file that looks like this too: https://github.com/xaque208/puppet-bsd/blob/master/.fixtures.yml

Though with the right module deps that you've included here.  Can you include that with this PR?

**Comment by SourceDoctor** [comment]
https://github.com/xaque208/puppet-openvpn/pull/69

**Comment by SourceDoctor** [comment]
@xaque208 something else here?

**Comment by xaque208** [comment]
Oh no, I just forgot to come back.  Thank you.

**Pull request merged**
